### ISSUE TITLE
TypeError: mime.lookup is not a function

### ISSUE THREAD

**Issue by elana-voss** [jamesseanwright/maze-generator#1]
`npm run watch` results in this error:

```
serving "dist" at http://127.0.0.1:8080
/mnt/c/Users/Erik/projects/maze-generator/node_modules/node-static/lib/node-static.js:348
                      mime.lookup(files[0]) ||
                           ^

TypeError: mime.lookup is not a function
    at Server.respond (/mnt/c/Users/Erik/projects/maze-generator/node_modules/node-static/lib/node-static.js:348:28)
    at /mnt/c/Users/Erik/projects/maze-generator/node_modules/node-static/lib/node-static.js:64:22
    at FSReqWrap.oncomplete (fs.js:154:5)
```

**Comment by jamesseanwright** [comment]
Really sorry I missed this! Which Node.js version are you running?
